/* === REVEAL ADAPTER AND FIXED STAGE === */
class SlidePresentation {
  constructor(){this.slides=[...document.querySelectorAll('.slide')];this.index=0;this.editing=false;this.key='ai-classification-classroom-v1';this.setupScale();this.setupEditing();this.setupControls();this.setupNavigation();this.start();}
  setupScale(){this.fit=()=>{const s=Math.min(innerWidth/1920,innerHeight/1080);document.querySelector('#deckStage').style.transform=`translate(${(innerWidth-1920*s)/2}px,${(innerHeight-1080*s)/2}px) scale(${s})`};addEventListener('resize',this.fit);this.fit();}
  async start(){await Reveal.initialize({width:1920,height:1080,disableLayout:true,center:false,controls:false,progress:false,keyboard:false,touch:false,hash:true,history:false,embedded:true,overview:false,transition:'none',autoAnimate:false});document.querySelectorAll('.backgrounds .slide').forEach(e=>e.classList.remove('slide'));Reveal.on('slidechanged',e=>this.sync(e.indexh));this.sync(Reveal.getIndices().h);this.fit();window.deckReady=true;}
  sync(index){this.index=index;this.slides.forEach((s,i)=>{s.classList.toggle('active',i===index);s.classList.remove('visible');s.setAttribute('aria-hidden',String(i!==index))});document.querySelector('#pageDisplay').textContent=`${index+1} / ${this.slides.length}`;document.querySelector('#progress').style.width=((index+1)/this.slides.length*100)+'%';document.querySelector('#prev').disabled=index===0;document.querySelector('#next').disabled=index===this.slides.length-1;if(!document.querySelector('#notesModal').hidden)this.updateNotes();}
  show(index){Reveal.slide(Math.max(0,Math.min(this.slides.length-1,index)))}
  blocked(e){return this.editing||!document.querySelector('#backdrop').hidden||e.target.closest('input,select,textarea,button,[contenteditable="true"]')}
  /* === KEYBOARD, POINTER AND TOUCH NAVIGATION === */
  setupNavigation(){addEventListener('keydown',e=>{const target=e.target.closest('input,textarea,select,[contenteditable="true"]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();this.export();return}if(e.key==='Escape'){this.close();if(this.editing)this.toggleEditing();return}if(!target&&e.key.toLowerCase()==='e'){e.preventDefault();this.toggleEditing();return}if(this.blocked(e))return;const k=e.key.toLowerCase();if(['arrowright','arrowdown',' ','pagedown'].includes(k)){e.preventDefault();this.show(this.index+1)}else if(['arrowleft','arrowup','pageup'].includes(k)){e.preventDefault();this.show(this.index-1)}else if(k==='home'){e.preventDefault();this.show(0)}else if(k==='end'){e.preventDefault();this.show(this.slides.length-1)}else if(k==='n')this.openNotes();else if(k==='g')this.openToc();else if(k==='f')this.fullscreen();});let last=0;addEventListener('wheel',e=>{if(this.blocked(e)||Math.abs(e.deltaY)<20)return;if(Date.now()-last>450){this.show(this.index+Math.sign(e.deltaY));last=Date.now()}},{passive:true});let touch=null;addEventListener('touchstart',e=>{if(this.blocked(e))return;touch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});addEventListener('touchend',e=>{if(!touch||this.blocked(e))return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))this.show(this.index+(dx<0?1:-1));touch=null},{passive:true});}
  /* === CONTENTS, NOTES AND FULLSCREEN === */
  setupControls(){document.querySelector('#prev').onclick=()=>this.show(this.index-1);document.querySelector('#next').onclick=()=>this.show(this.index+1);document.querySelector('#tocButton').onclick=()=>this.openToc();document.querySelector('#notesButton').onclick=()=>this.openNotes();document.querySelector('#fullButton').onclick=()=>this.fullscreen();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>this.close());document.querySelector('#backdrop').onclick=()=>this.close();document.querySelector('#search').oninput=e=>this.renderToc(e.target.value);}
  close(){document.querySelectorAll('.modal').forEach(m=>m.hidden=true);document.querySelector('#backdrop').hidden=true;}
  open(id){this.close();document.querySelector('#backdrop').hidden=false;document.querySelector(id).hidden=false;document.querySelector(id+' [data-close]').focus()}
  updateNotes(){const s=this.slides[this.index];document.querySelector('#notesTitle').textContent=`${this.index+1}. ${s.dataset.title}`;document.querySelector('#notesBody').innerHTML=s.querySelector('aside.notes')?.innerHTML||'<p>本页用于课程导览。</p>';}
  openNotes(){this.updateNotes();this.open('#notesModal');}
  renderToc(query=''){const list=document.querySelector('#tocList');list.replaceChildren();this.slides.forEach((s,i)=>{if(!s.dataset.title.includes(query))return;const b=document.createElement('button');b.textContent=`${String(i+1).padStart(3,'0')}　${s.dataset.title}`;if(s.classList.contains('chapter-slide'))b.className='chapter-item';b.onclick=()=>{this.show(i);this.close()};list.append(b)});}
  openToc(){this.renderToc();document.querySelector('#search').value='';this.open('#tocModal');document.querySelector('#search').focus();}
  async fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.querySelector('#editStatus').textContent='浏览器未允许全屏，可使用 F11';}}
  /* === INLINE EDITING: LOCAL STORAGE AND STANDALONE EXPORT === */
  setupEditing(){try{const saved=JSON.parse(localStorage.getItem(this.key)||'{}');document.querySelectorAll('[data-edit]').forEach(e=>{if(saved[e.dataset.edit]!==undefined)e.textContent=saved[e.dataset.edit]})}catch{}document.querySelector('#editToggle').onclick=()=>this.toggleEditing();const zone=document.querySelector('#editHotzone');let timer;zone.addEventListener('mouseenter',()=>{clearTimeout(timer);zone.classList.add('show')});zone.addEventListener('mouseleave',()=>{timer=setTimeout(()=>zone.classList.remove('show'),400)});document.querySelectorAll('[data-edit]').forEach(e=>e.addEventListener('input',()=>this.save()));}
  toggleEditing(){this.editing=!this.editing;document.body.classList.toggle('editing',this.editing);document.querySelectorAll('[data-edit]').forEach(e=>e.contentEditable=this.editing?'true':'false');document.querySelector('#editToggle').textContent=this.editing?'完成编辑 · E':'编辑 · E';if(!this.editing){document.activeElement.blur();this.save()}}
  save(){const data={};document.querySelectorAll('[data-edit]').forEach(e=>data[e.dataset.edit]=e.textContent);try{localStorage.setItem(this.key,JSON.stringify(data));document.querySelector('#editStatus').textContent='已自动保存到此浏览器 · Ctrl+S 导出 HTML'}catch{document.querySelector('#editStatus').textContent='请按 Ctrl+S 导出 HTML 保存修改'}}
  export(){this.save();const clone=document.documentElement.cloneNode(true);clone.querySelector('body').classList.remove('editing');clone.querySelectorAll('[contenteditable]').forEach(e=>e.removeAttribute('contenteditable'));clone.querySelectorAll('.modal').forEach(e=>e.hidden=true);clone.querySelector('#backdrop').hidden=true;clone.querySelector('#editToggle').textContent='编辑 · E';const blob=new Blob(['<!doctype html>\n'+clone.outerHTML],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AI的分类_课堂结构图_已编辑.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
}
window.presentation=new SlidePresentation();
