from pathlib import Path
import json,html
p=Path('outputs/video-notes/4.AI-本质/work');slides=[]
def add(title,body,scene,hint,kind=''):slides.append(dict(title=title,body=body,scene=scene,hint=hint,kind=kind))
def fine(x):return f'<p class="fine" data-edit>{x}</p>'
def take(x):return f'<p class="takeaway" data-edit>{x}</p>'
def steps(items):return '<div class="steps">'+''.join(f'<div data-edit>{a}<small>{b}</small></div>' for a,b in items)+'</div>'
def code(x):return '<pre class="code" data-edit>'+html.escape(x)+'</pre>'
def photo(n,cap):return '<figure><img src="{{image:'+str(n)+'}}" alt="'+cap+'"><figcaption>'+cap+'</figcaption></figure>'
def flow(items):return '<div class="flow">'+''.join(('<span class="arrow">→</span>' if i else '')+f'<div class="node{ " core" if i==1 else ""}" data-edit>{a}<small>{b}</small></div>' for i,(a,b) in enumerate(items))+'</div>'
add('AI 的本质', '<div class="title-line"></div><p class="subtitle" data-edit>透过输入与输出，理解不断变化的 AI 概念。</p><p class="title-meta" data-edit>模型 · 服务 · 应用<br>AI 基础 / 第四课</p>',1,'开场强调：本课交付一套理解方法。完整教程保留课堂原有顺序与全部讲解。','title')
add('每一层，都在封装下一层',steps([('AI Application','应用开发 / 工具使用'),('Model Service','封装裸模型调用'),('Raw Model','输入 → 运算 → 输出')])+take('先找准层次，再看概念落在哪里。'),1,'从下向上解释三层。这里的箭头和排列代表概念层次，不是一次请求的完整技术时序。')
add('边界会移动，事情总要有人做','<div class="comparison"><div><em>模型服务多做</em><p data-edit>应用少做</p><strong data-edit>例如部分 Skills、Tools 能力</strong></div><div><em>模型服务未做</em><p data-edit>应用补上</p><strong data-edit>交互逻辑仍然需要实现</strong></div></div>'+fine('功能归属以课堂示例为背景，具体依服务接口而定。'),2,'保留原课“你多做一点，我少做一点”的解释。不要把所有Skills实现等同于所有服务商都内置支持。')
add('调用方式稳定，能力仍在变化',flow([('Token List','输入'),('Raw Model','数学运算'),('概率分布','输出')])+take('训练、参数、性能可以迭代；观察入口与出口。'),2,'对应原课的底层稳定性判断。讲者强调的是调用的抽象形式，并非所有模型架构或接口细节永远不变。')
add('微调：别只计算训练时间','<div class="comparison"><div><em>课堂案例 · GPT-3.5</em><p data-edit>微调 + 验证</p><strong data-edit>两三个月，甚至半年</strong></div><div><em>模型更新 · GPT-4</em><p data-edit>直接调用新模型</p><strong data-edit>可能已超过之前的结果</strong></div></div>'+fine('原课判断与假设案例；人力验证成本是此处讨论重点。'),3,'完整保留内部知识、改权重、验证预期和新模型更新的推理。原课“很少有人微调”不是这里重新核验的行业事实，也不是普适建议。')
add('应用层有两条学习路线','<div class="comparison"><div><em>应用开发</em><p data-edit>做一个 AI 工具</p><strong data-edit>概念 + 框架 + 模型服务</strong></div><div><em>工具使用</em><p data-edit>用工具提升效率</p><strong data-edit>概念 + 具体工具操作</strong></div></div>'+fine('开发框架例子：LangChain · LangGraph · DeepAgent'),4,'编程工具属于应用层。课程介绍、福利课与薪资定位完整保留在教程第5章，讲授时可自行展开。')
add('工具会换，理解方法可以复用','<div class="quote" data-edit>先理解概念，<br>再看工具怎么用。</div>'+steps([('Claude Code','编程工具'),('Codex','编程工具'),('OpenCode','编程工具')])+fine('本课面向程序员，重点是 AI 编程工具。'),6,'原课还谈到AI短剧不在范围内、新奇工具寿命短。另一个工具名辨识存疑，只在详细备注和完整教程保留标记，不将猜测放大为重点。')
add('只盯住两个问题','<div class="duo" style="margin-top:50px"><div><em>01 / INPUT</em><p data-edit>输入什么<br>给模型？</p></div><div><em>02 / OUTPUT</em><p data-edit>如何处理<br>模型的输出？</p></div></div>'+take('“我给模型什么，它给我结果后，我怎么办？”'),7,'这里是本课核心论点。保留讲者钓鱼方法、新概念层出不穷的类比，并强调这是应用与服务层的分析视角。')
add('前处理与后处理，是现成例子',flow([('前处理','提示词 / Token 化'),('模型生成','输入 → 输出'),('后处理','反 Token 化 / 检查')])+take('应用也可能补充消息，再处理返回结果。'),8,'服务内部与应用外部都能沿输入输出观察。课堂中模型服务的前后处理是回顾，并非所有后处理只能做合规检查。')
add('用熟悉的 HTTP 帮助理解',steps([('请求','发什么内容 / 什么格式'),('交互','发几次 / 怎样继续'),('响应','回什么 / 如何处理')])+take('课堂类比：缓存、大文件上传、单点登录。'),9,'原画面写“协议缓存”。另一个OAuth术语识别不清，正文有标记；不在主屏以确定事实呈现。')
add('新概念到来，追踪三件事',steps([('01 · 输入','应用给模型传了什么？'),('02 · 输出','模型返回了什么？'),('03 · 后续','应用拿到结果又做了什么？')])+fine('接下来以 Skills 为例，沿真实消息走一遍。'),9,'强调Skills只是教学例子，方法可用于其他应用概念。避免把所有实现限制为完全相同的消息格式。')
add('把代理插进消息链路',flow([('Claude Code','来自用户的任务'),('代理服务器','记录请求与响应'),('模型服务','生成结果')])+take('请求向右转发；响应沿原路返回。')+fine('用户 ↔ Claude Code ↔ 代理服务器 ↔ 模型服务'),10,'先说明正常链路，再说明HTTPS抓包与自建代理两种观察方式。代理接收、转发、记录，未改变此处分析问题。')
add('先验证代理能转发', '<div class="split"><div>'+code('TARGET_URL=https://www.baidu.com\nPORT=3000\nLOG_LEVEL=debug')+'<p style="margin-top:32px" data-edit>npm run dev<br>curl http://localhost:3000/</p></div>'+photo(11,'日志记录请求头、请求体与响应')+'</div>'+fine('先把 .env.example 复制为 .env；百度仅为课堂连通性测试目标。'),11,'按顺序讲配置、启动、curl、检查日志。说明教程保留可见命令，但没有提供视频中代理项目的完整源码。')
add('应用请求代理，代理请求模型','<div class="split"><div><p class="lead" data-edit>两个地址<br>各司其职</p><p data-edit>应用端 → 本地代理<br>代理目标 → 模型服务</p></div>'+photo(12,'CC Switch 中启用 Kimi-Proxy')+'</div>'+fine('将目标从测试用百度改为 Kimi，再重启代理。'),12,'保留Claude Code通过CC Switch配置的演示，提醒“改应用请求地址”和“改代理转发目标”是两处配置。这里不展示或复制凭据。')
add('没输入问题，也可能有请求','<div class="split"><div><p data-edit>应用先测试连通性。</p><p data-edit>同时提交 tools，<br>定义 Skill 工具。</p><p data-edit>约定技能名与参数格式。</p></div>'+photo(13,'请求中的 Skill 工具描述')+'</div>',13,'先问听众：用户是否已经输入？还没有。再看JSON中的测试消息和tools，说明用户所见输入并不等于应用发送的完整上下文。')
add('“你是谁”的答案从哪里来？','<div class="comparison"><div><em>实际调用的模型</em><p data-edit>Kimi</p><strong data-edit>请求：kimi-for-coding</strong></div><div><em>模型生成的回答</em><p data-edit>“我是 Claude Code”</p><strong data-edit>应用提供了身份提示词</strong></div></div>'+take('查看完整输入，才能解释表面的回答。'),14,'不是根据回答去猜模型身份。原课通过请求中系统提示词定位身份信息，另外检查了CLAUDE.md与技能目录。')
add('技能清单先告诉模型“有哪些”','<div class="split"><div><p data-edit>技能名称</p><p data-edit>用途与触发时机</p><p data-edit>调用格式另由工具说明约定</p></div>'+photo(14,'system-reminder 中的技能清单')+'</div>'+fine('docker-compose · skill-create · web-design-guidelines'),14,'明确Skill工具描述、可用技能目录、具体技能全文是不同内容。此页用实际请求截图，不能把本次结构推广成所有产品规范。')
add('发出 review UX，触发技能','<div class="split"><div><p class="lead" data-edit>review UX</p><p data-edit>模型识别适用技能。</p><p data-edit>界面显示已加载，<br>随后询问要审查哪些文件。</p></div>'+photo(15,'成功加载 web-design-guidelines')+'</div>',15,'输入按画面修正为review UX。讲者暂不选择文件，转而去日志里检查模型响应。')
add('一句自然语言，还不是整个调用','<div class="comparison"><div><em>普通文本</em><p data-edit>“我将使用这个技能”</p><strong data-edit>显示给人阅读</strong></div><div><em>工具调用</em><p data-edit>tool_use + 参数</p><strong data-edit>让应用知道该执行什么</strong></div></div>'+fine('模型响应通过 SSE 分段返回，需继续查看后面的结构化内容。'),16,'按原课观察顺序，先定位自然语言，再定位工具调用。不要把说“我要调用”本身当作已经执行。')
add('流式 JSON 要拼接后再理解','<div class="split"><div>'+code('event: content_block_delta\ndelta.type: input_json_delta\npartial_json: "web"\npartial_json: "-design"\npartial_json: "-guid"\npartial_json: "elines"')+'</div>'+photo(16,'日志里技能名分散在多个片段')+'</div>'+fine('为阅读整理的字段示意；不表示每段响应都按相同边界切分。'),16,'从画面里的event与data说明SSE。展示的是已见片段，不是完整API请求模板；完整结构与其他事件在原始画面中。')
add('模型选择，应用执行下一步',steps([('拿到输入','用户消息 + 提示词'),('是否用技能？','不需要则正常回答'),('需要技能','返回工具名和调用参数')])+take('Claude Code 收到后，继续读取技能文档。'),17,'举“你是谁”通常无需技能、review UX触发技能两个原课例子。此页聚焦第一轮，不跳过应用在模型外部的作用。')
add('用到技能时，再送入全文','<div class="comparison"><div><em>开始时</em><p data-edit>技能目录与描述</p><strong data-edit>让模型知道可用能力</strong></div><div><em>调用后</em><p data-edit>完整技能文档</p><strong data-edit>让模型继续按文档处理</strong></div></div>'+fine('课堂通过复制技能文档中的一句话，在下一轮请求中搜索验证。'),18,'补充图片在完整教程中展示tool_result与Web Interface Guidelines正文。保留读取本地文件的步骤和模型继续处理的返回路径。')
add('输入与输出，组成完整闭环','<div class="steps"><div data-edit>第一轮输入<small>用户需求 + 提示词</small></div><div data-edit>模型输出<small>技能调用 JSON</small></div><div data-edit>应用处理<small>读取完整技能文档</small></div></div><div class="steps" style="margin-top:36px"><div data-edit>第二轮输入<small>把文档交给模型</small></div><div data-edit>模型继续处理<small>生成后续消息</small></div><div data-edit>返回用户<small>通过 Claude Code 呈现</small></div></div>',18,'逐段问听众哪一步在构造输入、哪一步在处理输出。这个闭环是教学案例的流程重绘，不附加未在原课演示的行为。')
add('真正要带走的是观察方法','<div class="quote" data-edit>看它传了什么，<br>看它返回什么，<br>再看应用怎样继续。</div>'+fine('Skills 是例子。下一个新概念，也先从消息链路入手。'),19,'保留讲者对前端概念迭代和知识海洋的类比，核心是研究方法，而非承诺所有复杂系统只需几分钟即可理解。')
add('按目标，继续自己的学习路线','<div class="comparison"><div><em>希望提高个人效率</em><p data-edit>学习工具使用</p><strong data-edit>对应原课的高薪课路线</strong></div><div><em>希望构建团队工具</em><p data-edit>学习应用开发</p><strong data-edit>对应原课的架构课路线</strong></div></div>'+fine('原课课程介绍及后续安排完整保留在教程第 5、20 章。'),20,'如需完整复述，展开备注中的课程介绍和结尾。两个课程名称是源视频的课程体系，不是本稿新增的推荐或报名入口。')
add('输入什么？<br>输出之后做什么？','<p class="subtitle" data-edit>让每一个新概念，回到可观察的过程。</p><p class="title-meta" data-edit>完整讲解、原始画面与术语校读<br>请查看配套完整教程</p>',19,'以两个核心问题收束；需要复查原课论证和操作时，点击本页下方的完整教程链接。','title')
(p/'deck-data.json').write_text(json.dumps(slides,ensure_ascii=False,indent=2),encoding='utf-8')
print('Deck:',len(slides),'slides')
