from pathlib import Path
p=Path('work/raw-model-notes.py')
s=p.read_text(encoding='utf-8').replace('它输出的是个啥？','它输入的是个啥？').replace('两式用 === 比较','两式用 == 比较')
p.write_text(s,encoding='utf-8')
p=Path('work/raw-model-build.py')
s=p.read_text(encoding='utf-8').replace("r'\\A'.join", "r'\\A '.join")
s=s.replace('sections=[]',"css+='\\n.deck-controls{width:max-content;max-width:calc(100vw - 16px);white-space:nowrap}@media(max-width:500px){.deck-controls{font-size:11px;gap:3px;padding:5px 6px}.deck-controls button,.deck-controls a{padding:5px}}'\nsections=[]")
p.write_text(s,encoding='utf-8')
p=Path('work/raw-model-notes.py')
s=p.read_text(encoding='utf-8').replace('两式用 == 比较得到 false','两式比较得到 false')
p.write_text(s,encoding='utf-8')
p=Path('work/raw-model-verify.cjs')
s=p.read_text(encoding='utf-8').replace('[...document.images].filter(i=>!i.complete||!i.naturalWidth)',"[...document.querySelectorAll('figure img')].filter(i=>!i.complete||!i.naturalWidth)")
p.write_text(s,encoding='utf-8')
