const {chromium}=require('C:/Users/micro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const root=path.resolve('outputs/Transformer'),out=path.resolve('work/transformer/verify');fs.mkdirSync(out,{recursive:true});
(async()=>{
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:720}});let errors=[],external=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});
await page.goto(pathToFileURL(path.join(root,'Transformer-演示文稿.html')).href);await page.evaluate(()=>document.fonts.ready);
const count=await page.locator('.slide').count();let checks=[];const deckText=await page.locator('[data-unit] .unit-text').allTextContents();
for(let i=0;i<count;i++){
 await page.evaluate(n=>presentation.showSlide(n),i);await page.waitForTimeout(240);
 checks.push(await page.evaluate(()=>{const s=document.querySelector('.slide.active'),box=s.getBoundingClientRect(),foot=s.querySelector('.footer').getBoundingClientRect();return{title:s.getAttribute('aria-label'),overflow:[...s.querySelectorAll('h1,h2,p,.formula,.note,figure,.route,.subtitle')].filter(e=>{let b=e.getBoundingClientRect();return b.left<box.left-1||b.right>box.right+1||b.bottom>foot.top-6||e.scrollWidth>e.clientWidth+3||e.scrollHeight>e.clientHeight+3}).map(e=>({tag:e.tagName,text:e.innerText?.slice(0,75),bottom:e.getBoundingClientRect().bottom,footer:foot.top})),brokenImages:[...s.querySelectorAll('img')].filter(i=>!i.complete||!i.naturalWidth).length}}));
 await page.screenshot({path:path.join(out,`slide-${String(i+1).padStart(2,'0')}.png`)});
}
await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');const nav=await page.locator('#pageCount').innerText();await page.keyboard.press('g');await page.locator('#search').fill('注意力');const filtered=await page.locator('#jump li:visible').count();const before=await page.locator('#pageCount').innerText();await page.keyboard.press('ArrowRight');const inputGuard=before===await page.locator('#pageCount').innerText();await page.keyboard.press('Escape');await page.keyboard.press('e');const edit=await page.locator('[data-edit]').first().getAttribute('contenteditable');await page.keyboard.press('Escape');
const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);await download.saveAs(path.join(out,'saved-deck.html'));
await page.locator('#full').click();await page.waitForTimeout(250);const fullscreen=await page.evaluate(()=>({active:!!document.fullscreenElement,toolbar:getComputedStyle(document.querySelector('.deck-controls')).display}));await page.evaluate(()=>document.fullscreenElement&&document.exitFullscreen());
let mobile=[];for(const v of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(v);await page.evaluate(()=>presentation.showSlide(26));await page.waitForTimeout(250);mobile.push(await page.locator('.deck-stage').evaluate(e=>{let b=e.getBoundingClientRect();return{width:b.width,height:b.height,ratio:b.width/b.height,left:b.left,top:b.top}}));await page.screenshot({path:path.join(out,`mobile-${v.width}.png`)});}
await page.setViewportSize({width:1440,height:1000});await page.goto(pathToFileURL(path.join(root,'Transformer-图文文章.html')).href);await page.evaluate(()=>document.fonts.ready);
const articleText=await page.locator('[data-unit] .unit-text').allTextContents();const sameContent=JSON.stringify(articleText)===JSON.stringify(deckText);
const article=await page.evaluate(()=>({sections:document.querySelectorAll('article section').length,images:document.querySelectorAll('figure img').length,broken:[...document.querySelectorAll('figure img')].filter(i=>!i.complete||!i.naturalWidth).length,anchors:[...document.querySelectorAll('nav a')].every(a=>document.querySelector(a.hash)),overflow:document.documentElement.scrollWidth>innerWidth+2}));
await page.screenshot({path:path.join(out,'article-desktop.png')});await page.locator('#u27').scrollIntoViewIfNeeded();await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'article-attention.png')});await page.locator('#u27 img').first().click();const zoom=await page.locator('dialog').isVisible();await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'article-mobile.png')});const mobileArticle=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));
const sourceTraces=await page.evaluate(()=>document.body.innerText.match(/原视频|视频截图|视频转写|视频总结|讲者|转写|回看|时间戳|\d{2}:\d{2}/g));
const result={errors,external,slides:count,slideChecks:checks,navigation:nav,indexResults:filtered,inputGuard,editing:edit,fullscreen,downloadBytes:fs.statSync(path.join(out,'saved-deck.html')).size,mobile,article,mobileArticle,zoom,sameContent,sourceTraces};
fs.writeFileSync(path.join(out,'browser-audit.json'),JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify({...result,slideChecks:checks.filter(c=>c.overflow.length||c.brokenImages)},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
