const {chromium}=require('C:/Users/micro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'outputs/Transformer'),shots=path.join(root,'work/transformer/verify/interactive');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));
const open=async n=>{const file=fs.readdirSync(out).find(f=>f.startsWith(n+'-')&&f.endsWith('.html'));await page.goto('file:///'+path.join(out,file).replace(/\\/g,'/'));};
const set=async (id,v)=>page.locator('#'+id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))},v);
await open('02');await page.evaluate(()=>lab.go(6));const q=await page.evaluate(()=>lab.audit.all);await set('inputValue',2);assert.notDeepEqual(await page.evaluate(()=>lab.audit.all.Q),q.Q);await page.evaluate(()=>lab.reset());await page.locator('#role').selectOption('V');await page.evaluate(()=>lab.go(6));const before=await page.evaluate(()=>lab.audit.all);await set('weightValue',2);const after=await page.evaluate(()=>lab.audit.all);assert.deepEqual(before.Q,after.Q);assert.deepEqual(before.K,after.K);assert.notDeepEqual(before.V,after.V);await page.evaluate(()=>lab.go(3));await page.screenshot({path:path.join(shots,'02-final.png'),fullPage:true});
await open('03');const a=await page.evaluate(()=>lab.audit);await page.locator('#kind').selectOption('V');await set('cellValue',4);const b=await page.evaluate(()=>lab.audit);assert.deepEqual(a.weights,b.weights);assert.notDeepEqual(a.out,b.out);await page.locator('#scaled').uncheck();assert.notDeepEqual(await page.evaluate(()=>lab.audit.weights),a.weights);const zeros=await page.evaluate(()=>lab.math.norm([2,2,2]));assert.deepEqual(zeros.y,[0,0,0]);const stable=await page.evaluate(()=>lab.math.softmax([1000,1001,-1000]));assert(stable.every(Number.isFinite));await page.evaluate(()=>lab.go(4));await page.screenshot({path:path.join(shots,'03-softmax.png'),fullPage:true});
await open('06');await page.evaluate(()=>lab.go(2));const on=await page.evaluate(()=>lab.audit.out);await page.locator('#relu').uncheck();assert.notDeepEqual(await page.evaluate(()=>lab.audit.out),on);await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(shots,'06-network-mobile.png'),fullPage:true});const size=await page.locator('.network').evaluate(svg=>{const t=svg.querySelector('text');return parseFloat(getComputedStyle(t).fontSize)*svg.getScreenCTM().a});assert(size>=11);await page.setViewportSize({width:1440,height:1000});
await open('07');await set('layers',6);assert.equal(await page.evaluate(()=>lab.count),24);await page.evaluate(()=>lab.go(23));assert.equal(await page.evaluate(()=>lab.audit.layer),5);await set('layers',1);assert.equal(await page.evaluate(()=>lab.step),3);assert.equal(await page.evaluate(()=>lab.count),4);
await open('08');await page.evaluate(()=>lab.go(7));assert.equal(await page.evaluate(()=>lab.audit.done),true);await page.getByRole('button',{name:'上一步',exact:true}).click();assert.equal(await page.evaluate(()=>lab.audit.prefix.length),6);await page.getByRole('button',{name:'↺ 重置',exact:true}).click();assert.equal(await page.evaluate(()=>lab.audit.prefix.length),0);
await open('09');assert.equal(await page.evaluate(()=>lab.audit.weights[2][3]),0);await page.locator('#masked').uncheck();assert((await page.evaluate(()=>lab.audit.weights[2][3]))>0);await page.locator('#masked').check();await page.locator('#position').selectOption('0');assert.deepEqual(await page.evaluate(()=>lab.audit.weights[0]),[1,0,0,0,0,0,0]);
await open('10');const cross=await page.evaluate(()=>lab.audit);assert.equal(cross.heads[0].weights.length,7);assert.equal(cross.heads[0].weights[0].length,3);assert.notDeepEqual(cross.heads[0].weights,cross.heads[1].weights);
await open('12');await page.evaluate(()=>lab.go(6));await page.locator('#mode').selectOption('encoder');assert.equal(await page.evaluate(()=>lab.count),3);assert.equal(await page.evaluate(()=>lab.step),2);await page.locator('[data-stage="0"]').first().click();assert.equal(await page.evaluate(()=>lab.step),0);await page.locator('#mode').selectOption('decoder');assert.equal(await page.evaluate(()=>lab.count),5);await page.locator('#reset').click();assert.equal(await page.evaluate(()=>lab.state.mode),'both');
// Keyboard control and a playback run reaching its end.
await page.locator('h1').click();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>lab.step),1);await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>lab.step),0);await page.evaluate(()=>lab.go(lab.count-2));await page.locator('#speed').selectOption('800');await page.getByRole('button',{name:'播放',exact:true}).click();await page.waitForTimeout(950);assert.equal(await page.evaluate(()=>lab.playing),false);assert.equal(await page.evaluate(()=>lab.step),6);await page.getByRole('button',{name:'播放',exact:true}).click();assert.equal(await page.evaluate(()=>lab.step),0);await page.getByRole('button',{name:'暂停',exact:true}).click();await page.locator('#play').hover();const color=await page.locator('#play').evaluate(x=>({bg:getComputedStyle(x).backgroundColor,fg:getComputedStyle(x).color}));assert.equal(color.bg,'rgb(40, 94, 86)');
// All links within every new page resolve, including return-to-article anchors.
const article=fs.readFileSync(path.join(out,'Transformer-图文文章.html'),'utf8');for(const file of fs.readdirSync(out).filter(n=>n.endsWith('交互演示.html')||n==='Transformer-交互演示目录.html')){const html=fs.readFileSync(path.join(out,file),'utf8');for(const [,href] of html.matchAll(/href="([^"#]+)(?:#([^" ]+))?"/g)){if(href.startsWith('http'))continue;const name=href.split('#')[0];assert(fs.existsSync(path.join(out,name)),file+' broken '+name)}const anchor=html.match(/Transformer-图文文章.html#(u\d+)/)?.[1];if(anchor)assert(article.includes(`id="${anchor}"`));}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(shots,'edge-audit.json'),JSON.stringify({passed:true,keyboard:true,parameterEffects:true,stableMath:true,allLinks:true,mobileSvgTextPx:size,playHover:color},null,2));console.log('Edge cases, parameter effects, keyboard, links and mobile SVG passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
